executor:
    plugin: k8s
    k8s:
        options:
            kubernetes:
                host: process.env.K8S_HOST
                token: process.env.K8S_TOKEN
            launchVersion: stable

scms:
    github:
        plugin: github
        config:
            oauthClientId: process.env.SECRET_OAUTH_CLIENT_ID
            oauthClientSecret: process.env.SECRET_OAUTH_CLIENT_SECRET
            secret: process.env.SECRET_SECRET
            username: sd-buildbot
            email: dev-null@screwdriver.cd
